# Generated by Django 3.0.5 on 2020-04-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('uploaded_by', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField()),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
