# Generated by Django 3.0.5 on 2020-04-07 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
